# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  format-and-lint:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "format code"
          command: "go fmt ./..."

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - format-and-lint